version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    environment:
      PYTHONUNBUFFERED: "1"
      PYTHONDONTWRITEBYTECODE: "1"
      GALILEU_URL: ${GALILEU_URL}
      GALILEU_TOKEN: ${GALILEU_TOKEN}
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_POCKETBASE_URL: "http://localhost:8090"
        VITE_FASTAPI_URL: "http://localhost:8000"
    container_name: vite-frontend
    ports:
      - "5000:5000"
    restart: unless-stopped

  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    command:
      - --encryptionEnv
      - ENCRYPTION
    environment:
      ENCRYPTION: $(openssl rand -hex 16)
    ports:
      - "8090:8090"
    volumes:
      - ./pocketbase/pb_data:/pb_data
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
      - pocketbase
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /dev/null:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
